### PR TITLE
Start realtimer from initial pts

### PR DESCRIPTION
**Pull request by philipgiuliani**
We have the case that we are maintaining the timestamps of a HLS livestream. When starting the livestream in the middle, the dts/pts would already be some minutes in the future, which would cause the real timer to never emit any packet.

With this change, the first packet will be emitted as soon as the Realtimer starts and from there on the timer will start working properly.

### CODE REVIEW

**Comment by dmorn** [comment]
Please have another look at this implementation! I added a test case that shows our, and we think also yours, preferred behaviour. Basically the realtimer starts being itself from the first packet onwards, thats its 0 timestamp.

**Comment by mat-hek** [comment]
Hi @dmorn, sorry for missing this! Looks great ✅

**Comment by gBillal** [comment]
@mat-hek can we have a new release !!

**Comment by mat-hek** [comment]
@gBillal published ;)

**Pull request merged**
